from __future__ import annotations


QUEUE_SCHEMAS: dict[str, list[str]] = {
    "source_dossiers": [
        "source_id",
        "source_type",
        "title",
        "author_or_speaker",
        "participants",
        "date_created",
        "date_consumed",
        "date_added",
        "original_file_path",
        "url",
        "context",
        "short_summary",
        "main_claims",
        "worldview_or_perspective",
        "relevant_hypotheses",
        "reliability_notes",
        "bias_or_framing_notes",
        "my_notes",
        "processing_status",
    ],
    "source_triage": [
        "source_id",
        "triage_status",
        "priority_0_5",
        "recommended_action",
        "relevance_tags",
        "summary",
        "key_claims",
        "reasons_for_attention",
        "reasons_to_skip",
        "cluster",
        "reviewer",
        "triaged_at",
        "notes",
    ],
    "evidence_clusters": [
        "cluster_id",
        "cluster_title",
        "core_question",
        "description",
        "hypotheses_touched",
        "topic_tags",
        "status",
        "created_date",
        "updated_date",
        "notes",
    ],
    "source_cluster_members": [
        "cluster_id",
        "source_id",
        "source_role",
        "subtopic",
        "relevance_0_5",
        "priority_0_5",
        "status",
        "notes",
    ],
    "extracted_claims": [
        "claim_id",
        "source_id",
        "claim_text",
        "claim_type",
        "argument_summary",
        "source_context",
        "quoted_excerpt",
        "related_hypotheses",
        "supports_hypotheses",
        "undermines_hypotheses",
        "possible_defeater_for",
        "uncertainty_notes",
        "status",
    ],
    "criteria_matrix": [
        "claim_id",
        "source_id",
        "relevance_0_5",
        "reliability_0_5",
        "clarity_0_5",
        "argument_strength_0_5",
        "explanatory_power_0_5",
        "scope_0_5",
        "defeater_strength_0_5",
        "uncertainty_0_5",
        "existential_salience_0_5",
        "moral_stakes_0_5",
        "emotional_salience_0_5",
        "practical_consequences_0_5",
        "notes",
    ],
    "proposed_updates": [
        "proposal_id",
        "claim_id",
        "source_id",
        "evidence_argument",
        "category",
        "source_book",
        "suggested_weight_0_5",
        "EC_MI5",
        "PC_MI5",
        "PT_MI5",
        "CT_MI5",
        "MT_MI5",
        "IS_MI5",
        "MS_MI5",
        "HC_MI5",
        "N_MI5",
        "notes",
        "suggestion_rationale",
        "uncertainty_notes",
        "review_status",
    ],
    "approved_updates": [
        "proposal_id",
        "claim_id",
        "source_id",
        "evidence_argument",
        "category",
        "source_book",
        "approved_weight_0_5",
        "EC_MI5",
        "PC_MI5",
        "PT_MI5",
        "CT_MI5",
        "MT_MI5",
        "IS_MI5",
        "MS_MI5",
        "HC_MI5",
        "N_MI5",
        "notes",
        "approved_by",
        "approved_date",
        "export_status",
        "exported_at",
        "exported_workbook",
        "export_verification_report",
    ],
    "rejected_updates": [
        "proposal_id",
        "claim_id",
        "source_id",
        "evidence_argument",
        "rejection_reason",
        "rejected_by",
        "rejected_date",
        "notes",
    ],
    "deferred_updates": [
        "proposal_id",
        "claim_id",
        "source_id",
        "evidence_argument",
        "deferral_reason",
        "revisit_date",
        "deferred_by",
        "deferred_date",
        "notes",
    ],
    "import_log": [
        "log_id",
        "timestamp",
        "operation",
        "file_path",
        "status",
        "message",
    ],
    "change_log": [
        "change_id",
        "timestamp",
        "operation",
        "input_file",
        "output_file",
        "status",
        "details",
    ],
}

REFLECTION_JOURNAL_TEMPLATE = """# Reflection Journal

Use this space for brief process notes, review reflections, and questions to revisit.

## Entries

"""

MI5_COLUMNS = ["EC_MI5", "PC_MI5", "PT_MI5", "CT_MI5", "MT_MI5", "IS_MI5", "MS_MI5", "HC_MI5", "N_MI5"]

WEIGHT_FIELDS = {
    "proposed_updates": ["suggested_weight_0_5"],
    "approved_updates": ["approved_weight_0_5"],
}

CRITERIA_SCORE_FIELDS = [
    "relevance_0_5",
    "reliability_0_5",
    "clarity_0_5",
    "argument_strength_0_5",
    "explanatory_power_0_5",
    "scope_0_5",
    "defeater_strength_0_5",
    "uncertainty_0_5",
    "existential_salience_0_5",
    "moral_stakes_0_5",
    "emotional_salience_0_5",
    "practical_consequences_0_5",
]
